name: Deploy to Github Pages

on:
  pull_request:
    types: [closed]
    
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
  
    - name: Build Project
      run: ng build --configuration production

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        
        github_token: ${{ secrets.TOKEN_MELODY }}
        publish_dir: ./dist/mon-appli
