name: Deploy to Github Pages

on:
  pull_request:
    types: [closed]
    
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: ng build --prod

    - name: Deploy
      uses: angular-schule/gh-pages-deploy@v0.3
      with:
        dir: dist/mon-application
